### ISSUE TITLE
Indication of the XEP version supported

### ISSUE THREAD

**Issue by Neustradamus** [noonien-d/pidgin-xmpp-receipts#5]
Can you add in the README, the current XEP-0184 version supported (XEP-XXXX v1.2)?

Examples:
- https://metronome.im/supported-xeps-list
- https://dev.gajim.org/gajim/gajim/wikis/help/gajimxepsupport
- https://github.com/jappix/jappix/blob/master/PROTOCOL.md

**Comment by noonien-d** [comment]
Done, thanks for the hint.

**Comment by Neustradamus** [comment]
@noonien-d: Thanks for the change, can you update the code for be complete and up-to-date?
